name: Check code formatting

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check code formatting
        run: npm run lint
